apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assignment3hpa
  namespace: mamb0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: your-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
---
