apiVersion: v1
kind: Service
metadata:
  name: assignment2service
  namespace: mamb0
spec:
  selector:
    app: yourapp
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
  type: NodePort

